db:
  build: ./mysql
  ports:
   - "3306:3306"
  environment:
    MYSQL_PASS: "6gdP7R3adDYNehj"
server:
  build: .
  ports:
   - "9000:80"
  expose:
   - "80"
  links:
   - "db:db"
  environment:
    NODE_ENV: development
    PORT: 80